services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    
    env_file:
      - .env
    
    depends_on:
      db:
        condition: service_healthy
        
    entrypoint: sh -c "python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15-alpine
    
    env_file:
      - .env
      
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: