# Generated by Django 5.1.5 on 2025-10-31 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("wallets", "0002_wallet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="name",
            field=models.CharField(default="Default", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="wallet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="wallets.wallet",
            ),
            preserve_default=False,
        ),
    ]
