# Generated by Django 5.1.5 on 2025-10-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="name",
            field=models.CharField(default="Default", max_length=100),
            preserve_default=False,
        ),
    ]
