# Generated by Django 5.1.5 on 2025-11-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_wallet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
